{% set python_min = '3.11' %}
{% set name = "pyrasa" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrasa-{{ version }}.tar.gz
  sha256: 338fb9709cd0c2c7baa2536b12894df33d7333f8f8775a222a8bedf83956aa48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26,<3
    - pandas >=2.1,<3
    - scipy >=1.12
    - attrs

test:
  imports:
    - pyrasa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Spectral parametrization based on IRASA
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/schmidtfa/pyrasa

extra:
  recipe-maintainers:
    - thht
    - schmidtfa
